# Generated by Django 5.1.3 on 2024-11-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_alter_employee_email_alter_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeid',
            field=models.IntegerField(),
        ),
    ]
