# Generated by Django 5.1.3 on 2024-11-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_alter_employee_employeeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
